# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 159de00aecc263ad97a42b3b6ba2e9e125d7276ae1883d5634401269a635131aeaa6a41a8f4095e825f007d9a8f1d8fa0c055bac2edba0cf3b74fe1b1ecba1ee

test:
  secret_key_base: 04c2ab00f2bbaefb1270ddec6cbe10a9f779ad9fe4d0e82856b68a9f8b87a4cbc5119312b3df26dcae0b889dac5ac831b4f46eafa7ca1d3c472f95626756c0a0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
